/**
 * Bilingual strings (Traditional Chinese - Hong Kong style on top, British English below).
 * Every UI string lives here so the same dictionary can be re-used by both
 * the React Native app and the static web build.
 */

export const STR = {
  app: {
    titleZh: '瑞士制輪數計算機',
    titleEn: 'Swiss Round Calculator',
    // The word "瑞士" should appear underlined in the rendered title.
    titleUnderlineZh: '瑞士',
    footnoteZh: '本應用程式由黃汶聰編寫及設計。版權所有 © 2026 黃汶聰。保留所有權利。',
    footnoteEn:
      'This app is written and designed by Man Chong Wong. Copyright © 2026 Man Chong Wong. All rights reserved.',
    footnoteUnderline: '黃汶聰',
  },
  onboarding: {
    headerZh: '使用前同意',
    headerEn: 'Please Agree Before Use',
    agreeZh: '本人已閱讀並同意以下文件：',
    agreeEn: 'I have read and agree to the following documents:',
    ppZh: '私隱權政策',
    ppEn: 'Privacy Policy',
    eulaZh: '終端使用者授權合約',
    eulaEn: 'End-User License Agreement',
    tcZh: '條款及細則',
    tcEn: 'Terms and Conditions',
    discZh: '免責聲明',
    discEn: 'Disclaimer',
    acceptZh: '我接受',
    acceptEn: 'I Accept',
    checkingZh: '正在核對訂閱狀態…',
    checkingEn: 'Checking subscription status…',
    offlineNoteZh: '離線時間（裝置）：',
    offlineNoteEn: 'Offline date/time (device): ',
  },
  paywall: {
    titleZh: '訂閱 瑞士制輪數計算機',
    titleEn: 'Subscribe to Swiss Round Calculator',
    bodyZh:
      '解鎖完整功能，年費自動續訂。除非於到期前 24 小時取消，否則訂閱將自動續期。可隨時於 App Store／Google Play 設定中取消。',
    bodyEn:
      'Unlock all features with an annual auto-renewing subscription. Unless cancelled at least 24 hours before the end of the period, the subscription renews automatically. You may cancel at any time in your App Store / Google Play settings.',
    subscribeZh: '訂閱',
    subscribeEn: 'Subscribe',
    restoreZh: '恢復購買',
    restoreEn: 'Restore Purchase',
    laterZh: '稍後',
    laterEn: 'Later',
    pricePrefixZh: '價格：',
    pricePrefixEn: 'Price: ',
    pricePerYearZh: '／年',
    pricePerYearEn: ' / year',
  },
  reminder: {
    titleZh: '訂閱即將到期',
    titleEn: 'Subscription Expiring Soon',
    bodyZh: (date) => `您的訂閱將於 ${date} 到期。如需續訂，請按「續訂」。`,
    bodyEn: (date) =>
      `Your subscription will expire on ${date}. Tap "Extend Subscription" to renew.`,
    priceChangeZh: (oldP, newP) =>
      `價格將由 ${oldP} 調整為 ${newP}。續訂即代表您確認接受新價格。`,
    priceChangeEn: (oldP, newP) =>
      `The price will change from ${oldP} to ${newP}. By extending you confirm acceptance of the new price.`,
    okZh: '確定',
    okEn: 'OK',
    extendZh: '續訂',
    extendEn: 'Extend Subscription',
  },
  errors: {
    cancelledZh: '購買已取消。',
    cancelledEn: 'Purchase cancelled.',
    failedZh: '訂閱失敗，請稍後再試。',
    failedEn: 'Subscription failed. Please try again later.',
    restoreOkZh: '已成功恢復購買。',
    restoreOkEn: 'Purchase restored successfully.',
    restoreFailZh: '未找到可恢復的購買。',
    restoreFailEn: 'No purchase to restore.',
    offlineZh: '目前離線。功能可能受限。',
    offlineEn: 'You are currently offline. Some features may be limited.',
  },
  tournament: {
    sectionZh: '賽事參數',
    sectionEn: 'Tournament Parameters',
    nNameZh: '人數',
    nNameEn: 'Number of Players',
    nSym: '(n)',
    nDescZh: '參賽人數（至少為4且必須是正整數）',
    nDescEn: 'Total Number of Players (at least 4 and must be positive integer)',
    pNameZh: '頂層選手數目',
    pNameEn: 'Placements at the top',
    pSym: '(p)',
    pDescZh: '頂層需準確地決出名次的人數（至多等於n且必須是正整數）',
    pDescEn: 'Accurate Ranks to determine (at most equals to n and must be positive integer)',
    dNameZh: '積分層距離',
    dNameEn: 'Score Group Distance',
    dSym: '(d)',
    dDescZh: '自尾二輪開始避免頂層選手遇上積分層距離達d（至少為2且必須是正整數）的對手',
    dDescEn:
      'Score Group Distance (at least 2 and must be positive integer) of the opponents against whom the top p players not to play starting from the second last round',
  },
  results: {
    sectionZh: '特定結果',
    sectionEn: 'Specific Results',
    roundsNameZh: '輪數',
    roundsNameEn: 'Rounds',
    roundsSym: '(Rmin - Rmax)',
    roundsDescZh:
      '準確地決出首<p>名選手所需的最少輪數及建議的最多輪數而超過此數目的輪數將屬多餘',
    roundsDescEn:
      'Minimum number of rounds required to accurately determine top <p> placements and Maximum number of rounds recommended that more rounds beyond the number are redundant',
    erNameZh: '淘汰賽輪數',
    erNameEn: 'Elimination Rounds',
    erSym: '(ERmin - ERmax)',
    erDescZh: '在對應的最少及最多輪數下，建議附加的淘汰賽輪數',
    erDescEn:
      'Suggested numbers of elimination rounds that go beyond the Swiss rounds for the respective minimum and maximum rounds',
    lNameZh: '能容許的最多負局數',
    lNameEn: 'Tolerable Maximum Losses',
    lSym: '(LmaxRmin - LmaxRmax)',
    lDescZh: '在對應的最少及最多輪數下，選手為擠身頂層所能容許的最多負局數',
    lDescEn:
      'Maximum number of losses that a player could tolerate to secure a placement in the top <p> for the respective minimum and maximum rounds',
    copyZh: '複製輸出',
    copyEn: 'Copy Output',
    copyStringZh: (n, p, rmin, rmax) =>
      `從${n}名參賽者中準確地決出首${p}名選手至少需要${rmin}輪，但不建議多於${rmax}輪。`,
    copyStringEn: (n, p, rmin, rmax) =>
      `To accurately determine top ${p} players out of ${n} participants, it takes at least ${rmin} rounds, though more than ${rmax} is not recommended.`,
    copiedZh: '已複製。',
    copiedEn: 'Copied.',
  },
  reverse: {
    sectionZh: '輪數逆向搜索',
    sectionEn: 'Reverse Round Lookup',
    rNameZh: '輪數',
    rNameEn: 'Rounds',
    rSym: '(r)',
    rDescZh: '（至少為3且必須是正整數）',
    rDescEn: '(at least 3 and must be positive integer)',
    rangeNameZh: '支援人數範圍',
    rangeNameEn: 'Supported Player Range',
    rangeSym: '(Nmin - Nmax)',
    rangeDescZh:
      '在對應輸入的<r>輪下，需要準確地決出首<p>名選手，可以接受的最少與最多參賽人數',
    rangeDescEn:
      'Minimum and Maximum number of players accepted to accurately determine top <p> placements for the respective input <r> rounds',
    lNameZh: '能容許的最多負局數',
    lNameEn: 'Tolerable Maximum Losses',
    lSym: '(LmaxNmin - Lmax - LmaxNmax)',
    lDescZh:
      '在對應輸入的<n>人或最少或最多支援人數及<r>輪下，選手為擠身頂層所能容許的最多負局數',
    lDescEn:
      'Maximum number of losses that a player could tolerate to secure a placement in the top <p> for the respective input <n> players or minimum or maximum supported players and input <r> rounds',
  },
  matrix: {
    sectionZh: '對應的輪數與人數範圍矩陣表',
    sectionEn: 'Corresponding Matrix Tableau of Rounds and Player Ranges',
    sectionDescZh: '隨頂層選手數目（p=<p>）變化',
    sectionDescEn: 'Varies with Top (p=<p>) Placements',
    rowRoundsZh: '輪數',
    rowRoundsEn: 'Rounds',
    rowRoundsSym: '(Rmin - Rmax)',
    rowERZh: '淘汰賽輪數',
    rowEREn: 'Elimination Rounds',
    rowERSym: '(ERmin - ERmax)',
    rowLZh: '最多負局數',
    rowLEn: 'Maximum Losses',
    rowLSym: '(LmaxRmin - LmaxRmax)',
    rowRangeZh: '人數範圍',
    rowRangeEn: 'Player Range',
  },
  note: {
    sectionZh: '備註：',
    sectionEn: 'Note:',
    p1Zh: '為保守起見，即使存在和局，仍使用無和局的二項式分佈公式，因為和局會使積分分佈更為分散，從而減少頂層的選手數量——因此，即使有和局發生，將其作為下界也是安全的。',
    p1En:
      "The no-draw binomial formula is used for conservative reason even when draws exist because draws spread the point distribution more, reducing the number of players at the top — so it's safe to use as a lower bound even when draws occur.",
    p2Zh: '在假設勝、和、負結果的概率時，這裏簡單地採用了二項式分佈，而不是複雜的多項式分佈或常態分佈。',
    p2En:
      'The binomial distribution is taken for simplicity reason instead of the complex multinomial distribution or the complicated normal distribution in assuming the probability of the results of wins, draws, and losses.',
    p3Zh: '這裏假設計分制使用了標準的1-0.5-0制。分出勝負的對局與和局的得分不一樣的計分制，或負局得分不是0的，則不限於此公式。',
    p3En:
      'The point-scoring system of 1-0.5-0 is assumed. This formula does not apply to point-scoring systems where the total score of a decisive game is not the same as the total score of a draw game, or if there is a non-zero loss score.',
  },
  nav: {
    funcZh: '公式',
    funcEn: 'Functions',
    setZh: '設定',
    setEn: 'Settings',
    legalZh: '法律',
    legalEn: 'Legal',
    wongZh: '黃氏計分法',
    wongEn: 'Wong system',
  },
  settings: {
    themeZh: '主題',
    themeEn: 'Theme',
    lightZh: '淺色',
    lightEn: 'Light',
    darkZh: '深色',
    darkEn: 'Dark',
    orientZh: '畫面方向鎖定',
    orientEn: 'Orientation Lock',
    autoZh: '自動',
    autoEn: 'Auto',
    landscapeZh: '橫向（左）',
    landscapeEn: 'Landscape Left',
    portraitZh: '直向',
    portraitEn: 'Portrait',
    orientWebDisabledZh: '（網頁版不適用）',
    orientWebDisabledEn: '(N/A on web)',
    restoreZh: '恢復購買',
    restoreEn: 'Restore Purchase',
    resetZh: '重設參數',
    resetEn: 'Reset Parameters',
    manageZh: '管理訂閱',
    manageEn: 'Manage Subscription',
    manageHintZh: '在裝置設定中管理或取消訂閱項目',
    manageHintEn: 'Manage or cancel subscriptions in your device settings',
    versionZh: '版本',
    versionEn: 'Version',
  },
  legal: {
    ppZh: '私隱權政策',
    ppEn: 'PP',
    eulaZh: '終端使用者授權合約',
    eulaEn: 'EULA',
    tcZh: '條款及細則',
    tcEn: 'T&C',
    discZh: '免責聲明',
    discEn: 'Disclaimer',
    enOnlyZh: '※ 此文件只提供英文版本。',
    enOnlyEn: '* This document is available in English only.',
  },
  about: {
    titleZh: '關於',
    titleEn: 'About',
  },
  common: {
    closeAria: 'Close',
  },
};

export const URLS = {
  pp: 'https://vviinncceenntt.github.io/swiss-round-calculator/privacy-policy.html',
  eula: 'https://vviinncceenntt.github.io/swiss-round-calculator/eula.html',
  tc: 'https://vviinncceenntt.github.io/swiss-round-calculator/terms.html',
  disc: 'https://vviinncceenntt.github.io/swiss-round-calculator/disclaimer.html',
  func: 'https://vviinncceenntt.github.io/swiss-round-calculator/functions.html',
  wong: 'https://vviinncceenntt.github.io/wongssystem.html',
  iosManage: 'https://apps.apple.com/account/subscriptions',
  androidManage: 'https://play.google.com/store/account/subscriptions',
};

export const DEFAULTS = {
  n: 193,
  p: 8,
  d: 4,
  rPlaceholder: 12,
  nMin: 4, nMax: 5001,
  pMin: 1, pMaxAbs: 5001,
  dMin: 2, dMax: 9999,
  rMin: 3, rMax: 5001,
};
